# docker compose -f docker-compose-gpu.yml -p media_process up -d --build
# docker compose -f docker-compose-gpu.yml -p media_process down -v
# print(torch.cuda.is_available())
# print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

version: '3.12.8'

services:
  fastapi_app:
    platform: linux/amd64  # This is the platform of the host machine
    build:
      context: .
      dockerfile: ./api/Dockerfile-gpu
    container_name: fastapi_app
    ports:
      - "8008:8008"
#    restart: on-failure
    # If you want to pass environment variables, add them here
    environment:
      - ENV=production
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]