FROM tensorflow/tensorflow:2.12.0-gpu

#FROM tensorflow/tensorflow:latest-gpu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-pip \
        ffmpeg \
        libsndfile1 \
        build-essential \
        cmake \
        libgtk-3-dev \
        cargo \
        libboost-all-dev && \
    rm -rf /var/lib/apt/lists/*


# Create and switch to a working directory
WORKDIR /app
ENV PYTHONPATH=/app
# Copy requirements.txt from the build context into the container
COPY ./api/requirements-gpu.txt .

# Install Python dependencies
RUN pip install --no-cache-dir --break-system-packages -r requirements-gpu.txt

# Copy the entire context into /app
COPY . /app
# Debug: List files to confirm structure
RUN find /app -type f
# Expose the port
EXPOSE 8008

# Run the FastAPI application via python -m
CMD ["sh", "-c", "uvicorn api.main:app --host 0.0.0.0 --port 8008 --workers 1 & celery -A api.celery_worker.celery_app worker --loglevel=info"]


